server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://210.109.60.99:10102/surveydb
    username: admin
    password: password123 # 각자 mysql password 설정하세용

  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true  # sql 쿼리 보여줌
        format_sql: true  # 쿼리 예쁘게 !

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace  # query의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여줌

  mail:
    host: smtp.gmail.com
    port: 587
    username: viewer2323@gmail.com # 한소연 개인계정임
    password: oeqnqeccbbtqxjnd
    properties:
      mail:
        smtp:
          starttls:
            enable: true

#security:
#  oauth2:
#    client:
#      registration:
#        kakao:
#          client-id: 1dc9c6c354c8d2390b7d0299842b6fae
#          redirect-uri: [Redirect URI]
#          authorization-grant-type: authorization_code
#          client-authentication-method: POST
#          client-name: Kakao
#          scope:
#            - profile_nickname
#            - account_email
#      provider:
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#          user-name-attribute: id