name: sync to gitlab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 # checkout
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1 # mirroring
        with:
          target_repo_url:
          git@210.109.60.59:10152/root/Back-End.git
          ssh_private_key:
          ${{ secrets.LEE }}
